FROM node:14
WORKDIR /usr/src/app
RUN echo 0.1.25
RUN apt-get update && \
    curl https://github.com/vendure-ecommerce/storefront/archive/v0.1.25.zip  -L -o storefront.zip && \
    unzip storefront.zip && \
    cp -a "storefront-angular-starter-0.1.25/."  . && \
    yarn
RUN yarn build:ssr:docker 
CMD ["node", "dist/server/main.js"]
EXPOSE 4000
VOLUME /usr/src/app
